### ISSUE TITLE
SOS / EOS tokens

### ISSUE THREAD

**Issue by torphix** [geronimi73/TinyLlama-versus-StableLM2#1]
Hey great note books!

Much appreciated
One question with regards to special tokens based on these docs: https://huggingface.co/stabilityai/stablelm-2-zephyr-1_6b
The SOS and EOS tokens used are:
```
<|user|>
Which famous math number begins with 1.6 ...?<|endoftext|>
<|assistant|>
The number you are referring to is 1.618033988749895. This is the famous value known as the golden ratio<|endoftext|>
```

and i think you are using <|im_start|> am i missing something or is this a mistake?

**Comment by geronimi73** [comment]
i'm using ChatML. looks like this:

```
<|im_start|>user
what does it mean to be successful?<|im_end|>
<|im_start|>assistant
Ahoy there, matey! To me, being successful means having the wind in your sails and reaching the treasure you've been dreaming of. It's about setting sail on a journey with clear goals, working hard, facing challenges head-on, and never losing sight of what truly matters. So, set your compass right, hoist your Jolly Roger high, and let's embark on this adventure together! ⚓️💰⛵️<|im_end|>
```

`eos` is `<|im_end|>` in all of my training code
also, I add `<|im_start|>` as a regular (non-special) token to tokenizer and model

this might be of interest too, makes prompt formatting a lot easier: https://huggingface.co/docs/transformers/main/en/chat_templating

**Comment by torphix** [comment]
Thanks!
